### PR TITLE
Update members-list.md

### PR DESCRIPTION
**Pull request by GauravPandey892**

### CODE REVIEW

**Comment by metonymic-smokey** [comment]
@GauravPandey892 could you please add a couple of spaces after each line, the way it's given in the format?
All your details are in one line right now.

Drop a message here if you need help with it.
Thanks!

**Comment by GauravPandey892** [comment]
Hey,
Is it fine now?

**Comment by GauravPandey892** [comment]
I did follow the format last time as well. I have added some spaces now. Does that help?

**Comment by metonymic-smokey** [comment]
@GauravPandey892 you have to add spaces after Link to Profile. The other lines are fine now.

And you could probably make a change to the same commit.

**Pull request merged**
