### PR TITLE
Update members-list.md

### PR DESCRIPTION
**Pull request by psiayn**

### CODE REVIEW

**Comment by RockieBhuvanesh** [comment]
Name: B Bhuvanesh 
SRN:PES1201801759 
ABOUT ME:Hi! My github name is Rockiebhuvanesh. Well I am a huge bleach fan. Love to lurk around in the internet looking for cool projects.

**Comment by anantvaid** [comment]
Name : Anant Vaid
SRN : PES2201800712
About : I'm a coding enthusiast and trying to learn new concepts. Currently, I've learnt JavaScript (with React and Redux)

**Comment by tfidfwastaken** [comment]
@RockieBhuvanesh @anantvaid @harsha613 
Guys, you're commenting on someone else's Pull Request.  
You all are supposed to make your own.  
Refer to the instructions in the `README.md` file in this repository. Also stick to the template you've been given.

If you are still having trouble, contact us [here](https://pesos.github.io/contact/).

**Comment by psiayn** [comment]
> Hello @psiayn!
> If you find something cool in your lurking adventures, do share 'em with the community.
> Oh, and welcome to the community XD

Sure!!

**Comment by tfidfwastaken** [comment]
Hey @psiayn, looks like you aren't in our Slack group yet.
You'll find it [here](https://pesos.github.io/get-started/communication-channels)

**Pull request merged**
